apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  namespace: db-monitoring
  labels:
    app: mysqld-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  template:
    metadata:
      labels:
        app: mysqld-exporter
    spec:
      containers:
        - name: mysqld-exporter
          image: prom/mysqld-exporter:v0.16.0
          ports:
            - containerPort: 9104
              name: metrics
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-exporter-secret
                  key: data-source-name
---
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: db-monitoring
  labels:
    app: mysqld-exporter
spec:
  selector:
    app: mysqld-exporter
  ports:
    - name: metrics
      port: 9104
      targetPort: metrics
