apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dns

resources:
  - namespace.yaml
  - configmap-dnsdist.yaml
  - configmap-unbound.yaml
  - configmap-vector-dnstap.yaml
  - deployment-dns-resolver.yaml
  - service-dns-resolver.yaml
  - servicemonitor-prometheus.yaml

commonLabels:
  app: dns-resolver
  managed-by: kustomize
  version: v1.01

