all:
  children:
    fortigate_fw:
      hosts:
        forti_fw_01:
          ansible_host: 10.0.0.10
    cisco_core_switch:
      hosts:
        cisco_core_01:
          ansible_host: 10.0.0.20
    cisco_l2l3_switch:
      hosts:
        cisco_access_01:
          ansible_host: 10.0.0.30
    f5_internal_lb:
      hosts:
        f5_internal_01:
          ansible_host: 10.0.0.40
    f5_external_lb:
      hosts:
        f5_external_01:
          ansible_host: 10.0.0.50
