apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespace.yaml
  - ../../exporters/mysql/deployment.yaml
  - ../../exporters/mysql/service-monitor.yaml
  - ../../exporters/mssql/deployment.yaml
  - ../../exporters/mssql/service-monitor.yaml
  - ../../rules/db-alert-rules.yaml
