#!/bin/bash

# 添加 DNS Zone 的輔助腳本

set -e

if [ -z "$1" ]; then
    echo "用法: ./add-zone.sh <domain> [ip_address]"
    echo ""
    echo "範例:"
    echo "  ./add-zone.sh example.com 192.0.2.100"
    echo ""
    exit 1
fi

DOMAIN=$1
IP_ADDRESS=${2:-"192.0.2.100"}
ZONE_FILE="bind/zones/db.${DOMAIN}"
CONFIG_FILE="bind/config/named.conf.local"

echo "📝 添加 DNS Zone: ${DOMAIN}"
echo ""

# 檢查 Zone 文件是否已存在
if [ -f "$ZONE_FILE" ]; then
    echo "⚠️  警告: Zone 文件已存在: ${ZONE_FILE}"
    read -p "是否覆蓋? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ 取消操作"
        exit 1
    fi
fi

# 創建 Zone 文件
echo "📄 創建 Zone 文件: ${ZONE_FILE}"
cat > "$ZONE_FILE" <<EOF
;
; BIND data file for ${DOMAIN}
; Generated by add-zone.sh
;

\$TTL    3600
\$ORIGIN ${DOMAIN}.

@       IN      SOA     ns1.${DOMAIN}. admin.${DOMAIN}. (
                        $(date +%Y%m%d)01      ; Serial (YYYYMMDDNN)
                        3600            ; Refresh (1 hour)
                        1800            ; Retry (30 minutes)
                        604800          ; Expire (1 week)
                        86400           ; Minimum TTL (1 day)
                        )

        ; Name Servers
        IN      NS      ns1.${DOMAIN}.
        IN      NS      ns2.${DOMAIN}.

        ; A Records
        IN      A       ${IP_ADDRESS}
www     IN      A       ${IP_ADDRESS}
ns1     IN      A       ${IP_ADDRESS}
ns2     IN      A       ${IP_ADDRESS}

        ; MX Records (Mail Exchange)
        IN      MX      10 mail.${DOMAIN}.

        ; CNAME Records
mail    IN      CNAME   www.${DOMAIN}.

        ; TXT Records
        IN      TXT     "v=spf1 mx a ~all"
EOF

echo "✅ Zone 文件已創建"

# 檢查配置文件中是否已有此 Zone
if grep -q "zone \"${DOMAIN}\"" "$CONFIG_FILE"; then
    echo "⚠️  配置文件中已有此 Zone 的配置"
else
    echo "📝 添加 Zone 配置到 named.conf.local"
    cat >> "$CONFIG_FILE" <<EOF

zone "${DOMAIN}" {
    type master;
    file "/var/lib/bind/zones/db.${DOMAIN}";
    allow-update { none; };
    notify no;
};
EOF
    echo "✅ Zone 配置已添加"
fi

# 驗證 Zone 文件語法
echo ""
echo "🔍 驗證 Zone 文件語法..."
if docker ps | grep -q bind9-dns; then
    docker exec -it bind9-dns named-checkzone ${DOMAIN} /var/lib/bind/zones/db.${DOMAIN} 2>&1 || {
        echo "⚠️  Zone 文件語法檢查失敗（容器可能未運行）"
    }
else
    echo "⚠️  容器未運行，無法驗證語法"
    echo "   請先啟動容器: ./start.sh"
fi

echo ""
echo "✅ Zone 添加完成！"
echo ""
echo "📋 下一步："
echo "1. 檢查 Zone 文件: cat ${ZONE_FILE}"
echo "2. 重啟容器以載入新配置: docker-compose restart bind9"
echo "3. 測試 DNS: dig @127.0.0.1 ${DOMAIN}"

