all:
  children:
    fortigate_fw:
      hosts:
        forti_fw_prod_01:
          ansible_host: 10.10.0.10
    cisco_core_switch:
      hosts:
        cisco_core_prod_01:
          ansible_host: 10.10.0.20
    cisco_l2l3_switch:
      hosts:
        cisco_access_prod_01:
          ansible_host: 10.10.0.30
    f5_internal_lb:
      hosts:
        f5_internal_prod_01:
          ansible_host: 10.10.0.40
    f5_external_lb:
      hosts:
        f5_external_prod_01:
          ansible_host: 10.10.0.50
