const express = require('express');
const bodyParser = require('body-parser');
const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = 3000;

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.static('public'));

// 获取所有 zones
app.get('/api/zones', (req, res) => {
  const zonesDir = path.join(__dirname, '..', 'bind', 'zones');
  const configFile = path.join(__dirname, '..', 'bind', 'config', 'named.conf.local');
  
  try {
    if (!fs.existsSync(zonesDir)) {
      return res.json({ success: true, zones: [] });
    }
    
    const files = fs.readdirSync(zonesDir);
    const zones = [];
    
    // 读取配置文件获取 zone 信息
    let configContent = '';
    if (fs.existsSync(configFile)) {
      configContent = fs.readFileSync(configFile, 'utf8');
    }
    
    files.forEach(file => {
      if (file.startsWith('db.') && file !== 'db.example.com') {
        const domain = file.replace('db.', '');
        
        zones.push({
          domain: domain,
          file: file,
          enabled: configContent.includes(`zone "${domain}"`)
        });
      }
    });
    
    res.json({ success: true, zones });
  } catch (error) {
    res.json({ success: false, error: error.message });
  }
});

// 添加新的 zone
app.post('/api/zones', (req, res) => {
  const { domain, ip } = req.body;
  
  if (!domain || !ip) {
    return res.json({ success: false, error: '域名和 IP 地址都是必需的' });
  }
  
  const zoneFile = path.join(__dirname, '..', 'bind', 'zones', `db.${domain}`);
  const configFile = path.join(__dirname, '..', 'bind', 'config', 'named.conf.local');
  
  try {
    // 创建 zone 文件
    const zoneContent = `;
; BIND data file for ${domain}
; Generated by Web UI
;

$TTL    3600
$ORIGIN ${domain}.

@       IN      SOA     ns1.${domain}. admin.${domain}. (
                        ${Date.now().toString().slice(0, 10)}01      ; Serial
                        3600            ; Refresh
                        1800            ; Retry
                        604800          ; Expire
                        86400           ; Minimum TTL
                        )

        ; Name Servers
        IN      NS      ns1.${domain}.
        IN      NS      ns2.${domain}.

        ; A Records
        IN      A       ${ip}
www     IN      A       ${ip}
ns1     IN      A       ${ip}
ns2     IN      A       ${ip}

        ; MX Records
        IN      MX      10 mail.${domain}.

        ; CNAME Records
mail    IN      CNAME   www.${domain}.

        ; TXT Records
        IN      TXT     "v=spf1 mx a ~all"
`;
    
    fs.writeFileSync(zoneFile, zoneContent);
    
    // 添加到配置文件
    let configContent = '';
    if (fs.existsSync(configFile)) {
      configContent = fs.readFileSync(configFile, 'utf8');
    }
    
    // 检查是否已存在
    if (configContent.includes(`zone "${domain}"`)) {
      return res.json({ success: false, error: `Zone ${domain} 已存在` });
    }
    
    const zoneConfig = `
zone "${domain}" {
    type master;
    file "/var/lib/bind/zones/db.${domain}";
    allow-update { none; };
    notify no;
};
`;
    
    // 移除注释块并添加新配置
    configContent = configContent.replace(/\/\*[\s\S]*?\*\//g, '');
    configContent += zoneConfig;
    
    fs.writeFileSync(configFile, configContent);
    
    // 重启 BIND
    exec('docker-compose restart bind9', { cwd: path.join(__dirname, '..') }, (error) => {
      if (error) {
        console.error('重启 BIND 失败:', error);
      }
    });
    
    res.json({ success: true, message: `Zone ${domain} 已添加` });
  } catch (error) {
    res.json({ success: false, error: error.message });
  }
});

// 删除 zone
app.delete('/api/zones/:domain', (req, res) => {
  const { domain } = req.params;
  const zoneFile = path.join(__dirname, '..', 'bind', 'zones', `db.${domain}`);
  const configFile = path.join(__dirname, '..', 'bind', 'config', 'named.conf.local');
  
  try {
    // 删除 zone 文件
    if (fs.existsSync(zoneFile)) {
      fs.unlinkSync(zoneFile);
    }
    
    // 从配置文件中移除
    if (fs.existsSync(configFile)) {
      let configContent = fs.readFileSync(configFile, 'utf8');
      const zonePattern = new RegExp(`zone\\s+"${domain.replace(/\./g, '\\.')}"[^}]*\\{[^}]*\\};?\\s*`, 'gs');
      configContent = configContent.replace(zonePattern, '');
      fs.writeFileSync(configFile, configContent);
    }
    
    // 重启 BIND
    exec('docker-compose restart bind9', { cwd: path.join(__dirname, '..') }, (error) => {
      if (error) {
        console.error('重启 BIND 失败:', error);
      }
    });
    
    res.json({ success: true, message: `Zone ${domain} 已删除` });
  } catch (error) {
    res.json({ success: false, error: error.message });
  }
});

// 测试 DNS 查询
app.post('/api/test', (req, res) => {
  const { domain, type = 'A' } = req.body;
  
  if (!domain) {
    return res.json({ success: false, error: '域名是必需的' });
  }
  
  const digCommand = `dig @127.0.0.1 ${domain} ${type} +short`;
  
  exec(digCommand, { timeout: 5000 }, (error, stdout, stderr) => {
    if (error) {
      return res.json({ success: false, error: error.message });
    }
    
    const result = stdout.trim().split('\n').filter(line => line.length > 0);
    res.json({ success: true, result });
  });
});

// 获取 DNS 日志
app.get('/api/logs', (req, res) => {
  const logFile = path.join(__dirname, '..', 'bind', 'logs', 'query.log');
  
  try {
    if (fs.existsSync(logFile)) {
      const logs = fs.readFileSync(logFile, 'utf8');
      const lines = logs.split('\n').filter(line => line.trim()).slice(-50);
      res.json({ success: true, logs: lines });
    } else {
      res.json({ success: true, logs: [] });
    }
  } catch (error) {
    res.json({ success: false, error: error.message });
  }
});

// 获取容器状态
app.get('/api/status', (req, res) => {
  exec('docker ps --filter name=bind9-dns --format "{{.Status}}"', (error, stdout) => {
    if (error) {
      return res.json({ success: false, error: error.message });
    }
    
    const status = stdout.trim();
    res.json({ success: true, status: status || '未运行' });
  });
});

app.listen(PORT, () => {
  console.log(`🚀 BIND DNS Web UI 运行在 http://localhost:${PORT}`);
});

