apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mssql-exporter
  namespace: db-monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: mssql-exporter
  namespaceSelector:
    matchNames:
      - db-monitoring
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
