ansible_connection: httpapi
ansible_network_os: f5networks.f5_modules.bigip
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_user: YOUR_F5_USER
ansible_password: YOUR_F5_PASSWORD
