#!/bin/bash
echo "=========================================="
echo "AWS CLI 安裝指令"
echo "=========================================="
echo ""
echo "請在終端機中執行以下命令："
echo ""
echo "1. 修復 Homebrew 權限："
echo "   sudo chown -R \$(whoami) /opt/homebrew /Users/\$(whoami)/Library/Logs/Homebrew"
echo ""
echo "2. 安裝 AWS CLI："
echo "   brew install awscli"
echo ""
echo "3. 驗證安裝："
echo "   aws --version"
echo ""
echo "4. 配置 AWS 憑證："
echo "   aws configure"
echo ""
echo "5. 執行設定腳本："
echo "   cd $(pwd)"
echo "   ./setup-aws-key.sh"
echo ""
echo "=========================================="
echo "或一次執行所有命令："
echo "=========================================="
echo ""
echo "sudo chown -R \$(whoami) /opt/homebrew /Users/\$(whoami)/Library/Logs/Homebrew && \\"
echo "brew install awscli && \\"
echo "aws --version"
