const fallbackState={summary:{description:'若 JSON data source 載入失敗，control plane 會使用內建 fallback state。'},modules:[{id:'fallback',name:'Fallback Module',domain:'Control Plane',status:'info',description:'目前 JSON 資料來源不可用，請檢查 data/modules.json。',gates:{source:{status:'info',detail:'No external module data loaded'},security:{status:'info',detail:'Fallback mode only'},health:{status:'info',detail:'UI remains available for inspection'}},actions:[{id:'inspect-fallback',label:'Inspect Fallback State',detail:'顯示本地 fallback 模式資訊'}]}]};
const nav=document.getElementById('module-nav'),moduleList=document.getElementById('module-list'),summaryText=document.getElementById('summary-text'),summaryStats=document.getElementById('summary-stats'),detailTitle=document.getElementById('detail-title'),detailStatus=document.getElementById('detail-status'),detailDescription=document.getElementById('detail-description'),gateGrid=document.getElementById('gate-grid'),actionList=document.getElementById('action-list'),actionResult=document.getElementById('action-result'),recommendationPanel=document.getElementById('recommendation-panel'),actionHistory=document.getElementById('action-history'),historyFilter=document.getElementById('history-filter'),historySort=document.getElementById('history-sort'),historyClear=document.getElementById('history-clear'),historyOnlyChanged=document.getElementById('history-only-changed'),historyCompareA=document.getElementById('history-compare-a'),historyCompareB=document.getElementById('history-compare-b'),historyCompareRun=document.getElementById('history-compare-run');
let currentState=fallbackState,selectedModuleId=fallbackState.modules[0].id,historySnapshots=[];
const badgeClass=s=>s==='pass'?'badge pass':s==='hold'?'badge hold':s==='block'?'badge block':'badge info';
const diffLine=(a,b,label)=>`<li>${label}: ${a??'n/a'} → ${b??'n/a'}</li>`;
const diffItems=(a,b)=>[{label:'policy',from:a?.recommendedPolicy,to:b?.recommendedPolicy},{label:'evidence',from:a?.evidenceCount,to:b?.evidenceCount},{label:'artifacts',from:a?.artifactCount,to:b?.artifactCount},{label:'scope',from:a?.actionScope,to:b?.actionScope}];
function renderRetrievalEvidence(items=[]){if(!items.length)return '<p class="muted">No retrieval evidence available.</p>';return `<ul class="recommendation-list">${items.map(i=>`<li><strong>${i.path}</strong> [${i.record_type||'unknown'}] score=${i.score}<br>${i.summary||''}<br><span class="muted">schema=${i.schema_file||'n/a'} artifact=${i.artifact_source||i.path}</span></li>`).join('')}</ul>`;}
function renderSummary(){const total=currentState.modules.length,passCount=currentState.modules.filter(m=>m.status==='pass').length,holdCount=currentState.modules.filter(m=>m.status==='hold').length;summaryText.textContent=currentState.summary?.description||'Control plane summary unavailable.';summaryStats.innerHTML=`<div class="stat"><span class="muted">Modules</span><strong>${total}</strong></div><div class="stat"><span class="muted">Pass</span><strong>${passCount}</strong></div><div class="stat"><span class="muted">Hold</span><strong>${holdCount}</strong></div>`;}
function renderNav(){nav.innerHTML='';moduleList.innerHTML='';currentState.modules.forEach(module=>{const navBtn=document.createElement('button');navBtn.textContent=module.name;navBtn.className=module.id===selectedModuleId?'active':'';navBtn.onclick=()=>selectModule(module.id);nav.appendChild(navBtn);const card=document.createElement('button');card.className=`module-card ${module.id===selectedModuleId?'active':''}`;card.onclick=()=>selectModule(module.id);card.innerHTML=`<div class="section-header"><div><h4>${module.name}</h4><p>${module.domain}</p></div><span class="${badgeClass(module.status)}">${module.status}</span></div><p>${module.description}</p>`;moduleList.appendChild(card);});}
function renderDetails(){const module=currentState.modules.find(i=>i.id===selectedModuleId);if(!module)return;detailTitle.textContent=module.name;detailStatus.textContent=module.status;detailStatus.className=badgeClass(module.status);detailDescription.textContent=module.description;gateGrid.innerHTML='';Object.entries(module.gates).forEach(([key,gate])=>{const d=document.createElement('div');d.className='gate-card';d.innerHTML=`<div class="section-header"><h4>${key.toUpperCase()} Gate</h4><span class="${badgeClass(gate.status)}">${gate.status}</span></div><p>${gate.detail}</p>`;gateGrid.appendChild(d);});actionList.innerHTML='';module.actions.forEach(action=>{const btn=document.createElement('button');btn.className='action-btn';btn.innerHTML=`<strong>${action.label}</strong><p>${action.detail}</p>`;btn.onclick=()=>runAction(module,action);actionList.appendChild(btn);});}
function renderRecommendation(p){const ec=p.evidence_count??(p.possible_causes||[]).length,ac=p.artifact_count??(p.related_artifacts||[]).length,manifest=p.manifest||{},artifactSummary=manifest.artifact_summary||{},datasetSummary=manifest.dataset_summary||{},latestDataset=datasetSummary.latest_scoped_dataset||{},scannedDataset=datasetSummary.scanned_dataset||{};recommendationPanel.innerHTML=`<p>${p.summary||'No recommendation summary available.'}</p><div class="recommendation-meta"><span class="${badgeClass(p.recommended_policy||'info')}">${p.recommended_policy||'info'}</span><span class="${badgeClass(p.confidence||'info')}">confidence: ${p.confidence||'unknown'}</span><span class="badge info">source: ${p.recommendation_source||'unknown'}</span><span class="badge info">evidence: ${ec}</span><span class="badge info">artifacts: ${ac}</span><span class="badge info">approval: ${p.human_approval_required?'required':'optional'}</span></div><h4>Action Scope</h4><ul class="recommendation-list"><li>${p.action_scope||'none'}</li></ul><h4>Manifest</h4><ul class="recommendation-list"><li>${manifest.manifest_path||'none'}</li><li>returncode=${manifest.returncode??'n/a'}</li><li>artifact_files=${artifactSummary.file_count??'n/a'}</li><li>artifact_bytes=${artifactSummary.total_size_bytes??'n/a'}</li><li>latest_records=${latestDataset.record_count??'n/a'}</li><li>scanned_records=${scannedDataset.record_count??'n/a'}</li></ul><h4>Scoped Artifacts</h4><ul class="recommendation-list">${(p.scoped_artifacts||[]).map(i=>`<li>${i}</li>`).join('')||'<li>none</li>'}</ul><h4>Possible Causes</h4><ul class="recommendation-list">${(p.possible_causes||[]).map(i=>`<li>${i}</li>`).join('')}</ul><h4>Recommended Checks</h4><ul class="recommendation-list">${(p.recommended_checks||[]).map(i=>`<li>${i}</li>`).join('')}</ul><h4>Related Artifacts</h4><ul class="recommendation-list">${(p.related_artifacts||[]).map(i=>`<li>${i}</li>`).join('')}</ul><h4>Top Retrieval Evidence</h4>${renderRetrievalEvidence(p.retrieval_evidence||[])}`;}
function renderResult(p){actionResult.textContent=JSON.stringify(p,null,2);}
function renderDiff(prev,curr,onlyChanged=false){if(!prev)return '<p class="muted">No previous snapshot to compare.</p>';let rows=diffItems(prev,curr);if(onlyChanged)rows=rows.filter(i=>`${i.from??'n/a'}`!==`${i.to??'n/a'}`);if(!rows.length)return '<p class="muted">No changed fields.</p>';return `<ul class="recommendation-list">${rows.map(i=>`<li>${i.label}: ${i.from??'n/a'} → ${i.to??'n/a'}</li>`).join('')}</ul>`;}
function syncCompareOptions(items){if(!historyCompareA||!historyCompareB)return;const opts=items.map(i=>`<option value="${i.compareKey}">${i.moduleName} / ${i.actionLabel} / ${i.timestamp}</option>`).join('');historyCompareA.innerHTML=`<option value="">Compare A</option>${opts}`;historyCompareB.innerHTML=`<option value="">Compare B</option>${opts}`;}
function renderComparePanel(items){if(!historyCompareA||!historyCompareB)return '';const a=items.find(i=>i.compareKey===historyCompareA.value),b=items.find(i=>i.compareKey===historyCompareB.value);if(!a||!b)return '';return `<div class="history-compare-panel"><h4>Compare Selected A/B</h4>${renderDiff(a,b,historyOnlyChanged?.checked)}</div>`;}
function renderHistory(){const filter=historyFilter?.value||'',sort=historySort?.value||'desc',onlyChanged=historyOnlyChanged?.checked||false;let items=[...historySnapshots];if(filter)items=items.filter(i=>i.moduleId===filter);if(sort==='asc')items=items.slice().reverse();items=items.map((i,idx)=>({...i,compareKey:`${i.moduleId}-${i.actionId}-${idx}`}));syncCompareOptions(items);if(!items.length){actionHistory.innerHTML='<p class="muted">No action snapshots yet.</p>';return;}actionHistory.innerHTML=`${renderComparePanel(items)}${items.map((i,idx)=>`<div class="history-item"><strong>${i.moduleName} — ${i.actionLabel}</strong><p class="muted">policy=${i.recommendedPolicy} source=${i.recommendationSource}</p><p class="muted">evidence=${i.evidenceCount} artifacts=${i.artifactCount}</p><p class="muted"><code>${i.timestamp}</code></p><p class="muted">scope=${i.actionScope||'none'}</p><p class="muted">manifest=${i.manifest?.manifest_path||'none'}</p><p class="muted">scoped=${(i.artifactSources||[]).join(', ')||'none'}</p><h4>Diff vs previous</h4>${renderDiff(items[idx+1],i,onlyChanged)}${renderRetrievalEvidence(i.retrievalEvidence||[])}</div>`).join('')}`;}
async function loadHistory(){const filter=historyFilter?.value||'',sort=historySort?.value||'desc';try{const r=await fetch(`/api/action-history?module_id=${encodeURIComponent(filter)}&sort=${encodeURIComponent(sort)}`);if(!r.ok)throw new Error(`HTTP ${r.status}`);const p=await r.json();historySnapshots=Array.isArray(p)?p:[];renderHistory();}catch(e){console.warn('Failed to load action history.',e);renderHistory();}}
async function persistHistorySnapshot(snapshot){try{const r=await fetch('/api/action-history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const p=await r.json();historySnapshots=Array.isArray(p)?p:historySnapshots;renderHistory();}catch(e){console.warn('Failed to persist action history snapshot.',e);}}
async function clearHistory(){const filter=historyFilter?.value||'';try{const r=await fetch(`/api/action-history?module_id=${encodeURIComponent(filter)}`,{method:'DELETE'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const p=await r.json();historySnapshots=Array.isArray(p)?p:[];renderHistory();}catch(e){console.warn('Failed to clear action history.',e);}}
function recordHistorySnapshot(module,action,recommendation,artifactSources=[],actionScope='',manifest={}){const snapshot={moduleId:module.id,moduleName:module.name,actionId:action.id,actionLabel:action.label,timestamp:new Date().toLocaleString('zh-TW',{hour12:false}),recommendedPolicy:recommendation.recommended_policy||'unknown',recommendationSource:recommendation.recommendation_source||'unknown',evidenceCount:recommendation.evidence_count??0,artifactCount:recommendation.artifact_count??0,retrievalEvidence:recommendation.retrieval_evidence||[],artifactSources,actionScope,manifest};historySnapshots=[snapshot,...historySnapshots].slice(0,20);renderHistory();persistHistorySnapshot(snapshot);}
function runLocalMockAction(module,action){const timestamp=new Date().toLocaleString('zh-TW',{hour12:false});renderResult({module:module.name,action:action.label,status:'mock-executed',decision:module.status==='pass'?'pass':'hold',timestamp,note:'本地 dry-run adapter 不可用，退回前端 mock action。若要啟用真實本地 skeleton dry-run，請使用 server.py 啟動 control plane。'});}
async function loadRecommendation(moduleId,actionId='',actionScope=''){recommendationPanel.innerHTML='<p class="muted">Loading AI recommendation...</p>';try{const r=await fetch(`/api/recommendations?module_id=${encodeURIComponent(moduleId)}&action_id=${encodeURIComponent(actionId)}&action_scope=${encodeURIComponent(actionScope)}&latest_only=true`);if(!r.ok)throw new Error(`HTTP ${r.status}`);const p=await r.json();renderRecommendation(p);return p;}catch(e){console.warn('Recommendation API unavailable, using fallback recommendation.',e);const p={summary:'Recommendation API unavailable. Fallback guidance suggests human review before any privileged action.',possible_causes:['Local recommendation adapter not running','No external AI backend connected yet'],recommended_checks:['Review module gates','Inspect latest dry-run output','Use documented runbooks for manual verification'],related_artifacts:['06-DevTools/automation/control-plane/AI-RECOMMENDATION-SPEC.md'],confidence:'low',recommended_policy:'hold',recommendation_source:'frontend-fallback',evidence_count:0,artifact_count:1,retrieval_evidence:[],scoped_artifacts:[],action_scope:'',manifest:{},human_approval_required:true};renderRecommendation(p);return p;}}
async function runAction(module,action){actionResult.textContent='Running local dry-run adapter...';try{const r=await fetch('/api/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({moduleId:module.id,actionId:action.id})});if(!r.ok)throw new Error(`HTTP ${r.status}`);const p=await r.json();renderResult(p);const rec=await loadRecommendation(module.id,action.id,p.action_scope||'');recordHistorySnapshot(module,action,rec,p.artifact_sources||[],p.action_scope||'',p.manifest||rec.manifest||{});}catch(e){console.warn('Local dry-run adapter unavailable, using mock result.',e);runLocalMockAction(module,action);const rec=await loadRecommendation(module.id,action.id,'');recordHistorySnapshot(module,action,rec,[],'',rec.manifest||{});}}
function selectModule(moduleId){selectedModuleId=moduleId;renderNav();renderDetails();loadRecommendation(moduleId);}
function applyState(newState){currentState=newState?.modules?.length?newState:fallbackState;selectedModuleId=currentState.modules[0].id;renderSummary();renderNav();renderDetails();loadRecommendation(selectedModuleId);}
async function loadState(){try{const r=await fetch('./data/modules.json');if(!r.ok)throw new Error(`HTTP ${r.status}`);applyState(await r.json());}catch(e){console.warn('Failed to load control-plane JSON data source, using fallback.',e);applyState(fallbackState);}await loadHistory();}
if(historyFilter)historyFilter.onchange=()=>loadHistory(); if(historySort)historySort.onchange=()=>loadHistory(); if(historyClear)historyClear.onclick=()=>clearHistory(); if(historyOnlyChanged)historyOnlyChanged.onchange=()=>renderHistory(); if(historyCompareRun)historyCompareRun.onclick=()=>renderHistory();
loadState();
